### ISSUE TITLE
"A non-numeric value encountered" when using pagination in admin

### ISSUE THREAD

**Issue by bahlrbrian** [sjelfull/craft3-audit#55]
I can get it to work if I edit the URL to just use the page param, but otherwise the pagination automatically adds the following (clicking to page 2 of pagination):

`http://domain.com/admin/audit?page=%28%3Anum%29`

Stack:
```yii\base\ErrorException: A non-numeric value encountered in /Applications/MAMP/htdocs/bankcda/vendor/superbig/craft-audit/src/controllers/DefaultController.php:67

Stack trace:
#0 /Applications/MAMP/htdocs/bankcda/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'A non-numeric v...', '/Applications/M...', 67)
#1 /Applications/MAMP/htdocs/bankcda/vendor/superbig/craft-audit/src/controllers/DefaultController.php(67): craft\web\ErrorHandler->handleError(2, 'A non-numeric v...', '/Applications/M...', 67, Array)
#2 [internal function]: superbig\audit\controllers\DefaultController->actionIndex()
#3 /Applications/MAMP/htdocs/bankcda/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Applications/MAMP/htdocs/bankcda/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /Applications/MAMP/htdocs/bankcda/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('index', Array)
#6 /Applications/MAMP/htdocs/bankcda/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#7 /Applications/MAMP/htdocs/bankcda/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('audit/default/i...', Array)
#8 /Applications/MAMP/htdocs/bankcda/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('audit/default/i...', Array)
#9 /Applications/MAMP/htdocs/bankcda/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /Applications/MAMP/htdocs/bankcda/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /Applications/MAMP/htdocs/bankcda/web/index.php(21): yii\base\Application->run()
#12 {main}```

**Comment by sjelfull** [comment]
Thanks for reporting this. What version of Craft are you seeing this on?

**Comment by bahlrbrian** [comment]
Craft Solo 3.3.18.1

**Comment by sjelfull** [comment]
Right, this is a known issue. Will be fixed once 1.1 is out. I'm gonna try to speed it up, but probably can't make it until after the holidays.

**Comment by bahlrbrian** [comment]
Good to know, thanks! Let me know if you need anything else from me that would be helpful.

**Comment by andrew-kaslick** [comment]
Hi,

We just purchased a license and have come across this issue, which is preventing us from viewing the logs. Can the planned fix for this be pushed out?

Thanks!

**Comment by sjelfull** [comment]
Hey y'all, sorry for the holdup. Lifes comes at you fast.

In a sec 1.1 should show up. It fixes this issue.

**Comment by andrew-kaslick** [comment]
Thanks for getting that update out! Can you also update the version in the `composer.json`?

**Comment by sjelfull** [comment]
Woops. Updated release with updated `composer.json`.
